// AUTO-GENERATED by scripts/migrate-pages.mjs — do not edit by hand.
// Source: ../yarche/services.html
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: { absolute: "Услуги digital-агентства ЯРЧЕ в Минске — SEO, сайты, Telegram-боты, AI" },
  description: "Полный спектр digital-услуг для бизнеса в Беларуси: SEO-продвижение, создание сайтов, Telegram-боты, контент-агентство и внедрение искусственного интеллекта. Комплексный подход с синергией.",
  keywords: ["digital услуги Минск","интернет-маркетинг Беларусь","продвижение сайтов","разработка сайтов Минск"],
  alternates: { canonical: "/services" },
  openGraph: {
    title: "Услуги digital-агентства ЯРЧЕ в Минске — SEO, сайты, Telegram-боты, AI",
    description: "Полный спектр digital-услуг для бизнеса в Беларуси: SEO-продвижение, создание сайтов, Telegram-боты, контент-агентство и внедрение искусственного интеллекта. Комплексный подход с синергией.",
    url: "/services",
    type: 'website',
    images: [{ url: "https://yarche.by/images/og.jpg" }],
  },
};

const BODY = `<section class="inner-hero">
    <div class="hero-badge animate">Полный спектр digital-услуг</div>
    <h1 class="animate delay-1">Всё для <span class="highlight">роста</span> вашего бизнеса</h1>
    <p class="animate delay-2">Мы объединяем пять ключевых направлений digital-маркетинга в единую экосистему. Каждая услуга усиливает остальные — вместе они дают кратный результат.</p>
  </section>

  <section class="section" style="padding-top:20px;">

    <!-- WEB — HIGHLIGHTED -->
    <div class="service-full card-hot animate" href="/web"><div class="card-hot-border"></div>
      <div class="service-full-num" style="color:var(--orange);">★</div>
      <div class="service-full-content">
        <div class="service-full-header">
          <div class="service-full-icon" style="background:rgba(255,107,0,0.15);">💻</div>
          <h3 style="color:var(--orange);">🔥 Создание сайтов</h3>
        </div>
        <p class="service-full-desc">Сайт — центр вашей digital-экосистемы. Мы проектируем и разрабатываем современные веб-решения: от быстрых лендингов до сложных интернет-магазинов с интеграцией ЕРИП, CRM и складских систем. Адаптивный дизайн, высокая скорость загрузки, SEO-оптимизация из коробки. Используем React, Vue, WordPress, Tilda — выбираем стек под задачу. После запуска обеспечиваем техподдержку и развитие проекта.</p>
        <div class="service-full-tags">
          <span style="border-color:rgba(255,107,0,0.2); background:rgba(255,107,0,0.06);">Лендинги</span>
          <span style="border-color:rgba(255,107,0,0.2); background:rgba(255,107,0,0.06);">Корпоративные сайты</span>
          <span style="border-color:rgba(255,107,0,0.2); background:rgba(255,107,0,0.06);">Интернет-магазины</span>
          <span style="border-color:rgba(255,107,0,0.2); background:rgba(255,107,0,0.06);">Веб-приложения</span>
          <span style="border-color:rgba(255,107,0,0.2); background:rgba(255,107,0,0.06);">Редизайн</span>
          <span style="border-color:rgba(255,107,0,0.2); background:rgba(255,107,0,0.06);">Техподдержка</span>
        </div>
        <span class="service-link" style="color:var(--orange);">Подробнее и тарифы →</span>
      </div>
    </div>

    <!-- AI-СОТРУДНИК -->
    <div class="service-full animate" href="/seo">
      <div class="service-full-num">02</div>
      <div class="service-full-content">
        <div class="service-full-header">
          <div class="service-full-icon">🔍</div>
          <h3>SEO-продвижение</h3>
        </div>
        <p class="service-full-desc">Органический трафик — самый ценный канал привлечения клиентов. Мы выводим сайты в ТОП Google и Яндекс через глубокий технический аудит, сбор семантического ядра, внутреннюю и внешнюю оптимизацию. Работаем с коммерческими и информационными запросами, строим контент-стратегию, которая приносит целевых посетителей месяц за месяцем. Прозрачная аналитика: вы видите рост позиций, трафика и конверсий в реальном времени.</p>
        <div class="service-full-tags">
          <span>Технический аудит</span>
          <span>Семантическое ядро</span>
          <span>Линкбилдинг</span>
          <span>Контент для SEO</span>
          <span>Локальное SEO</span>
          <span>SERM</span>
        </div>
        <span class="service-link">Подробнее и тарифы →</span>
      </div>
    </div>

    <!-- CONTENT -->
    <div class="service-full animate" href="/ai-employee">
      <div class="service-full-num">03</div>
      <div class="service-full-content">
        <div class="service-full-header">
          <div class="service-full-icon">🦞</div>
          <h3>AI-сотрудник на базе OpenClaw</h3>
        </div>
        <p class="service-full-desc">Не бот и не ассистент — полноценный виртуальный работник. Развёрнутый на вашей инфраструктуре AI-агент, который ведёт переписку с клиентами через любые мессенджеры, обрабатывает входящие заявки, управляет календарём и задачами, готовит отчёты и принимает решения в рамках заданных полномочий. Работает 24/7, помнит всё и становится умнее с каждым днём.</p>
        <div class="service-full-tags">
          <span>OpenClaw</span>
          <span>Мультиканальность</span>
          <span>На вашем сервере</span>
          <span>24/7</span>
          <span>CRM-интеграция</span>
          <span>Проактивность</span>
        </div>
        <span class="service-link">Подробнее и тарифы →</span>
      </div>
    </div>

    <!-- SEO -->
    <div class="service-full animate" href="/content">
      <div class="service-full-num">04</div>
      <div class="service-full-content">
        <div class="service-full-header">
          <div class="service-full-icon">✍️</div>
          <h3>Контент-агентство</h3>
        </div>
        <p class="service-full-desc">Контент — топливо для всех digital-каналов. Наше агентство закрывает полный цикл: от стратегии и рубрикатора до продакшна и дистрибуции. Пишем SEO-тексты, снимаем видео, делаем дизайн и фото. Ведём корпоративные блоги, создаём email-рассылки и коммерческие материалы. Каждый текст, каждый кадр работает на конкретную бизнес-цель — привлечение, удержание или конверсию.</p>
        <div class="service-full-tags">
          <span>Копирайтинг</span>
          <span>Видеопродакшн</span>
          <span>Графический дизайн</span>
          <span>Фотосъёмка</span>
          <span>Email-маркетинг</span>
          <span>Ведение блога</span>
        </div>
        <span class="service-link">Подробнее и тарифы →</span>
      </div>
    </div>

    <!-- AI -->
    <div class="service-full animate" href="/ai">
      <div class="service-full-num">05</div>
      <div class="service-full-content">
        <div class="service-full-header">
          <div class="service-full-icon">🤖</div>
          <h3>Внедрение AI</h3>
        </div>
        <p class="service-full-desc">Искусственный интеллект — не модное слово, а инструмент, который уже сегодня экономит часы работы и увеличивает прибыль. Мы внедряем AI-чатботов для сайта и мессенджеров, автоматизируем обработку документов и заявок, настраиваем предиктивную аналитику и рекомендательные системы. Проводим AI-аудит бизнеса, строим дорожную карту трансформации и обучаем вашу команду работать с новыми инструментами.</p>
        <div class="service-full-tags">
          <span>AI-чатботы</span>
          <span>Автоматизация</span>
          <span>Предиктивная аналитика</span>
          <span>Генерация контента</span>
          <span>Рекомендации</span>
          <span>AI-консалтинг</span>
        </div>
        <span class="service-link">Подробнее и тарифы →</span>
      </div>
    </div>

    <!-- TELEGRAM-БОТЫ -->
    <div class="service-full animate" href="/tg-bots">
      <div class="service-full-num">06</div>
      <div class="service-full-content">
        <div class="service-full-header">
          <div class="service-full-icon">🤖</div>
          <h3>Telegram-боты</h3>
        </div>
        <p class="service-full-desc">Telegram — мессенджер номер один в Беларуси, и это идеальная платформа для бизнес-автоматизации. Мы разрабатываем ботов любой сложности: от простых уведомлений до полноценных магазинов с каталогом, корзиной и оплатой через ЕРИП. Боты для записи, бронирования, HR-процессов и внутренней коммуникации. Mini Apps с нативным интерфейсом. AI-ассистенты внутри Telegram. Клиент покупает, не выходя из чата — конверсия в разы выше.</p>
        <div class="service-full-tags">
          <span>Каталог и оплата</span>
          <span>ЕРИП</span>
          <span>CRM-интеграция</span>
          <span>AI-ассистент</span>
          <span>Mini Apps</span>
          <span>Уведомления</span>
        </div>
        <span class="service-link">Подробнее и тарифы →</span>
      </div>
    </div>

  </section>

  <div class="section-divider"></div>

  <!-- WHY COMPLEX -->
  <section class="section">
    <div class="section-label animate">Почему комплекс</div>
    <h2 class="section-title animate delay-1">Синергия услуг даёт кратный рост</h2>
    <p class="section-desc animate delay-2">Каждое направление усиливает остальные. SEO приводит трафик, контент удерживает внимание, сайт конвертирует, боты автоматизируют коммуникацию, AI-сотрудник закрывает рутину.</p>
    <div class="synergy-grid">
      <div class="synergy-card animate">
        <div class="synergy-formula">SEO + Контент</div>
        <p>SEO-оптимизированные статьи приводят органический трафик, который растёт месяц к месяцу без увеличения бюджета на рекламу.</p>
      </div>
      <div class="synergy-card animate delay-1">
        <div class="synergy-formula">Боты + CRM</div>
        <p>Telegram-бот квалифицирует лиды и передаёт горячих клиентов в CRM. Автоматическая воронка снижает стоимость обработки заявки в 5 раз.</p>
      </div>
      <div class="synergy-card animate delay-2">
        <div class="synergy-formula">Сайт + AI</div>
        <p>AI-чатбот на сайте квалифицирует лиды и снижает нагрузку на менеджеров, а персонализация увеличивает конверсию до 2×.</p>
      </div>
      <div class="synergy-card animate delay-3">
        <div class="synergy-formula">SEO + Сайт</div>
        <p>Технически оптимизированный сайт с правильной структурой быстрее индексируется и стабильно растёт в поисковой выдаче.</p>
      </div>
    </div>
  </section>

  <div class="section-divider"></div>

  <section class="section" style="text-align:center;">
    <h2 class="section-title animate" style="margin:0 auto 20px;">Готовы начать?</h2>
    <p class="section-desc animate delay-1" style="margin:0 auto 40px;">Расскажите о задаче — предложим оптимальную комбинацию услуг и рассчитаем стоимость.</p>
    <a class="btn-primary animate delay-2" href="/contact">Обсудить проект →</a>
  </section>`;

export default function Page() {
  return (
    <>
      <link rel="stylesheet" href="/pages/services.css" />
      <main data-page="services" dangerouslySetInnerHTML={{ __html: BODY }} />
    </>
  );
}
