// AUTO-GENERATED by scripts/migrate-pages.mjs — do not edit by hand.
// Source: ../yarche/tg-bots.html
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: { absolute: "Создание сайтов в Минске — лендинги, магазины, веб-приложения | ЯРЧЕ" },
  description: "Разработка сайтов для бизнеса в Беларуси: лендинги, корпоративные сайты, интернет-магазины с ЕРИП. UX-дизайн, SEO-оптимизация, техподдержка. От 1 500 BYN.",
  keywords: ["создание сайтов Минск","разработка сайтов Беларусь","интернет-магазин","лендинг","веб-разработка"],
  alternates: { canonical: "/web" },
  openGraph: {
    title: "Создание сайтов в Минске — лендинги, магазины, веб-приложения | ЯРЧЕ",
    description: "Разработка сайтов для бизнеса в Беларуси: лендинги, корпоративные сайты, интернет-магазины с ЕРИП. UX-дизайн, SEO-оптимизация, техподдержка. От 1 500 BYN.",
    url: "/web",
    type: 'website',
    images: [{ url: "https://yarche.by/images/og.jpg" }],
  },
};

const BODY = `<section class="inner-hero">
    <div class="hero-badge animate">Telegram-боты</div>
    <h1 class="animate delay-1">Боты, которые <span class="highlight">продают</span></h1>
    <p class="animate delay-2">Разрабатываем Telegram-ботов любой сложности — от уведомлений до полноценных магазинов с каталогом, оплатой через ЕРИП и AI-ассистентом. Клиент покупает, не выходя из чата.</p>
  </section>

  <section class="section" style="padding-top:20px;">
    <div class="section-label animate">Что разрабатываем</div>
    <h2 class="section-title animate delay-1">Telegram-боты для любого бизнеса</h2>
    <p class="section-desc animate delay-2">Telegram — мессенджер №1 в Беларуси. Мы создаём ботов, которые автоматизируют продажи, поддержку и коммуникацию с клиентами прямо в чате.</p>
    <div class="features-list">
      <div class="feature-item animate"><div class="feature-num">01</div><div><h4>Боты для продаж и каталогов</h4><p>Полноценный магазин прямо в Telegram: каталог товаров с фото и описанием, корзина, оформление заказа и оплата через ЕРИП или банковскую карту. Клиент покупает в два клика, не выходя из мессенджера — конверсия в разы выше, чем на сайте.</p></div></div>
      <div class="feature-item animate delay-1"><div class="feature-num">02</div><div><h4>Боты для записи и бронирования</h4><p>Автоматическая запись к специалистам, бронирование столиков, аренда залов. Интеграция с Google Calendar и вашей CRM. Напоминания клиентам за день и за час. Снижение no-show на 40%.</p></div></div>
      <div class="feature-item animate delay-2"><div class="feature-num">03</div><div><h4>AI-ассистенты в Telegram</h4><p>Умные боты на базе GPT, которые отвечают на вопросы клиентов 24/7, консультируют по продуктам и услугам, квалифицируют лиды и передают горячих клиентов менеджеру. Обучаются на ваших данных и документах.</p></div></div>
      <div class="feature-item animate delay-3"><div class="feature-num">04</div><div><h4>Mini Apps</h4><p>Полноценные веб-приложения внутри Telegram с нативным интерфейсом. Личные кабинеты, программы лояльности, сложные формы, интерактивные каталоги. Выглядят и работают как приложение, но не требуют установки.</p></div></div>
      <div class="feature-item animate delay-4"><div class="feature-num">05</div><div><h4>Боты для HR и внутренних процессов</h4><p>Автоматизация рутины внутри компании: онбординг новых сотрудников, сбор отчётов, согласование отпусков, опросы и голосования. Интеграция с Bitrix24, Notion, Google Sheets.</p></div></div>
      <div class="feature-item animate delay-5"><div class="feature-num">06</div><div><h4>Рассылки и уведомления</h4><p>Сегментированные рассылки по базе подписчиков, автоматические уведомления о статусе заказа, триггерные цепочки сообщений. Открываемость в Telegram — 80%+, это в 4 раза больше, чем email.</p></div></div>
    </div>
  </section>

  <div class="section-divider"></div>

  <section class="section">
    <div class="section-label">Цены на разработку</div>
    <h2 class="section-title">Стоимость разработки Telegram-ботов</h2>
    <div class="pricing-grid">
      <div class="price-card animate">
        <h4>Старт</h4><div class="price-desc">Простой бот для бизнеса</div>
        <div class="price-amount">от 350 BYN</div>
        <div class="price-period">срок: 1–2 недели</div>
        <ul class="price-features">
          <li>Меню и команды</li>
          <li>Уведомления и рассылки</li>
          <li>Форма заявки / обратной связи</li>
          <li>Базовая аналитика</li>
          <li>Инструкция по управлению</li>
        </ul>
        <a class="price-btn price-btn-outline" href="/contact?tariff=Старт (TG-бот)">Оставить заявку</a>
      </div>
      <div class="price-card featured animate delay-1">
        <h4>Бизнес</h4><div class="price-desc">Бот с интеграциями и логикой</div>
        <div class="price-amount">от 990 BYN</div>
        <div class="price-period">срок: 2–3 недели</div>
        <ul class="price-features">
          <li>CRM-интеграция</li>
          <li>Каталог товаров / услуг</li>
          <li>Онлайн-запись и бронирование</li>
          <li>Оплата через ЕРИП</li>
          <li>Админ-панель</li>
          <li>Поддержка 3 месяца</li>
        </ul>
        <a class="price-btn price-btn-filled" href="/contact?tariff=Бизнес (TG-бот)">Оставить заявку</a>
      </div>
      <div class="price-card animate delay-2">
        <h4>Платформа</h4><div class="price-desc">Mini App и сложная автоматизация</div>
        <div class="price-amount">от 2 490 BYN</div>
        <div class="price-period">срок: 3–5 недель</div>
        <ul class="price-features">
          <li>Telegram Mini App</li>
          <li>Полноценный магазин в боте</li>
          <li>AI-ассистент</li>
          <li>Интеграция со складом и 1С</li>
          <li>Мультиязычность</li>
          <li>Поддержка 6 месяцев</li>
        </ul>
        <a class="price-btn price-btn-outline" href="/contact?tariff=Платформа (TG-бот)">Оставить заявку</a>
      </div>
    </div>
  </section>

  <div class="section-divider"></div>

  <!-- EXPERT ARTICLE -->
  <section class="section">
    <div class="section-label animate">Экспертиза</div>
    <h2 class="section-title animate delay-1">Почему бизнесу нужен Telegram-бот</h2>
    <div class="article-section animate delay-2">
      <h3>Telegram — не просто мессенджер, а платформа для бизнеса</h3>
      <p>В Беларуси Telegram используют более 5 миллионов человек. Это не просто чат — это экосистема с платежами, мини-приложениями и бизнес-инструментами. Бот в Telegram — это ваш сотрудник, который работает 24/7, не болеет и не уходит в отпуск.</p>

      <h4>Конверсия выше, чем на сайте</h4>
      <p>Пользователь уже в Telegram — ему не нужно открывать браузер, ждать загрузки сайта, заполнять формы. Два клика — и заказ оформлен. Средняя конверсия ботов-магазинов — 15–20%, в то время как у сайтов — 2–5%. Разница в 5 раз — это не маркетинговый ход, а статистика наших клиентов.</p>

      <h4>Автоматизация, которая экономит деньги</h4>
      <p>Один бот заменяет 2–3 сотрудников на рутинных задачах: ответы на типовые вопросы, запись на услуги, обработка заказов, отправка уведомлений. При стоимости разработки от 350 BYN — бот окупается за первый месяц работы.</p>

      <blockquote>
        <p>«Telegram-бот — это не модная игрушка, а рабочий инструмент. Наши клиенты получают первые заказы через бота уже в день запуска. Главное — правильно спроектировать сценарии и интеграции. Бот должен решать конкретную бизнес-задачу, а не просто существовать.»</p>
        <div class="expert-badge">
          <div class="expert-avatar">ВВ</div>
          <div>
            <div class="expert-name"><a href="/team/vlad">Владислав Васильченко</a></div>
            <div class="expert-role">CEO, ЯРЧЕ</div>
          </div>
        </div>
      </blockquote>

      <h4>Интеграции: бот как часть экосистемы</h4>
      <p>Бот не работает изолированно — он связан с вашей CRM, складом, платёжной системой и аналитикой. Заказ из бота автоматически попадает в Битрикс или amoCRM, клиент получает уведомление о доставке, а вы видите полную воронку продаж в реальном времени.</p>
    </div>
  </section>`;

export default function Page() {
  return (
    <>
      <link rel="stylesheet" href="/pages/tg-bots.css" />
      <main data-page="tg-bots" dangerouslySetInnerHTML={{ __html: BODY }} />
    </>
  );
}
