// AUTO-GENERATED by scripts/migrate-pages.mjs — do not edit by hand.
// Source: ../yarche/contact.html
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: { absolute: "Контакты ЯРЧЕ — обсудить проект | Digital-агентство в Минске" },
  description: "Свяжитесь с digital-агентством ЯРЧЕ в Минске. Обсудим ваш проект и предложим оптимальное решение в течение 24 часов. Телефон, email, Telegram.",
  keywords: ["digital агентство контакты","ЯРЧЕ Минск","заказать сайт","заказать SEO"],
  alternates: { canonical: "/contact" },
  openGraph: {
    title: "Контакты ЯРЧЕ — обсудить проект | Digital-агентство в Минске",
    description: "Свяжитесь с digital-агентством ЯРЧЕ в Минске. Обсудим ваш проект и предложим оптимальное решение в течение 24 часов. Телефон, email, Telegram.",
    url: "/contact",
    type: 'website',
    images: [{ url: "https://yarche.by/images/og.jpg" }],
  },
};

const BODY = `<section class="inner-hero">
    <div class="hero-badge animate">Связаться с нами</div>
    <h1 class="delay-1">Давайте обсудим ваш <span class="highlight">проект</span></h1>
    <p class="animate delay-2">Расскажите о задаче — мы предложим оптимальное решение и рассчитаем стоимость в течение 24 часов.</p>
  </section>
  <section class="contact-section" style="padding-top:20px;">
    <div class="contact-grid">
      <div class="contact-form animate">
        <div class="form-group">
          <label>Ваше имя</label>
          <input type="text" placeholder="Как к вам обращаться?">
        </div>
        <div class="form-group">
          <label>Телефон или email</label>
          <input type="text" placeholder="+375 (__) ___-__-__ или email">
        </div>
        <div class="form-group">
          <label>Интересующая услуга</label>
          <div class="custom-select" data-value="">
            <div class="custom-select-trigger">
              <span>Выберите услугу</span>
              <svg width="12" height="8" viewBox="0 0 12 8" fill="none"><path d="M1 1.5L6 6.5L11 1.5" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>
            </div>
            <div class="custom-select-options">
              <div class="custom-select-option" data-val="Создание сайта">
                <span class="cso-icon">💻</span> Создание сайта
              </div>
              <div class="custom-select-option" data-val="SEO-продвижение">
                <span class="cso-icon">🔍</span> SEO-продвижение
              </div>
              <div class="custom-select-option" data-val="Создание бота TG">
                <span class="cso-icon">🤖</span> Создание бота TG
              </div>
              <div class="custom-select-option" data-val="Подключение AI-чатбота на сайт">
                <span class="cso-icon">💬</span> Подключение AI-чатбота на сайт
              </div>
              <div class="custom-select-option" data-val="Контент-агентство">
                <span class="cso-icon">✍️</span> Контент-агентство
              </div>
              <div class="custom-select-option" data-val="Внедрение AI">
                <span class="cso-icon">🧠</span> Внедрение AI
              </div>
              <div class="custom-select-option" data-val="Комплексный пакет">
                <span class="cso-icon">⚡</span> Комплексный пакет
              </div>
            </div>
          </div>
        </div>
        <div class="form-group">
          <label>Расскажите о проекте</label>
          <textarea placeholder="Опишите вашу задачу, бюджет и сроки..."></textarea>
        </div>
        <button class="form-submit">Отправить заявку →</button>
      </div>
      <div class="contact-info animate delay-2">
        <h3>Готовы сделать ваш бизнес ярче?</h3>
        <p>Оставьте заявку или свяжитесь с нами любым удобным способом. Мы ответим в течение 2 часов в рабочее время.</p>
        <div class="contact-detail">
          <div class="contact-detail-icon">📞</div>
          <div class="contact-detail-text">
            <div class="label">Телефон</div>
            <div class="value"><a href="tel:+375292460054">+375 (29) 246-00-54</a></div>
          </div>
        </div>
        <div class="contact-detail">
          <div class="contact-detail-icon">✉️</div>
          <div class="contact-detail-text">
            <div class="label">Email</div>
            <div class="value"><a href="mailto:b2b@yarche.by">b2b@yarche.by</a></div>
          </div>
        </div>
        <div class="contact-detail">
          <div class="contact-detail-icon">💬</div>
          <div class="contact-detail-text">
            <div class="label">Мессенджеры</div>
            <div class="value"><a href="https://t.me/yarche_by" target="_blank" style="color:var(--text);text-decoration:none;">Telegram</a> / <a href="viber://chat?number=%2B375292460054" style="color:var(--text);text-decoration:none;">Viber</a> / <a href="https://wa.me/375292460054" style="color:var(--text);text-decoration:none;">WhatsApp</a></div>
          </div>
        </div>
        <div class="contact-detail">
          <div class="contact-detail-icon">📍</div>
          <div class="contact-detail-text">
            <div class="label">Офис</div>
            <div class="value">Парк высоких технологий, Минск</div>
          </div>
        </div>
      </div>
    </div>
  </section>`;

export default function Page() {
  return (
    <>
      <link rel="stylesheet" href="/pages/contact.css" />
      <main data-page="contact" dangerouslySetInnerHTML={{ __html: BODY }} />
    </>
  );
}
