// AUTO-GENERATED by scripts/migrate-pages.mjs — do not edit by hand.
// Source: ../yarche/content.html
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: { absolute: "Контент-агентство в Минске — тексты, видео, дизайн | ЯРЧЕ" },
  description: "Контент-агентство полного цикла: копирайтинг, видеопродакшн, графический дизайн, фотосъёмка. Контент-стратегия и управление блогом для бизнеса в Беларуси.",
  keywords: ["контент-агентство Минск","копирайтинг","видеопродакшн Беларусь","контент-маркетинг","создание контента"],
  alternates: { canonical: "/content" },
  openGraph: {
    title: "Контент-агентство в Минске — тексты, видео, дизайн | ЯРЧЕ",
    description: "Контент-агентство полного цикла: копирайтинг, видеопродакшн, графический дизайн, фотосъёмка. Контент-стратегия и управление блогом для бизнеса в Беларуси.",
    url: "/content",
    type: 'website',
    images: [{ url: "https://yarche.by/images/og.jpg" }],
  },
};

const BODY = `<section class="inner-hero">
    <div class="hero-badge animate">Контент-агентство</div>
    <h1 class="animate delay-1">Контент, который <span class="highlight">работает</span> на бизнес</h1>
    <p class="animate delay-2">Полный цикл создания контента: от стратегии до продакшна. Тексты, видео, графика, фото — всё под ключ, с единым стилем и привязкой к бизнес-целям.</p>
  </section>

  <section class="section" style="padding-top:20px;">
    <div class="section-label animate">Что мы делаем</div>
    <h2 class="section-title animate delay-1">Контент на каждом этапе воронки</h2>
    <p class="section-desc animate delay-2">Привлечение, вовлечение, конверсия и удержание — для каждого этапа нужен свой формат и подход. Мы создаём контент, который ведёт клиента от первого касания до покупки.</p>
    <div class="features-list">
      <div class="feature-item animate"><div class="feature-num">01</div><div><h4>Копирайтинг и SEO-тексты</h4><p>Экспертные статьи для блога, описания товаров и услуг, лендинг-копирайтинг, email-рассылки и коммерческие предложения. Каждый текст проходит SEO-оптимизацию и редактуру. Пишем на русском и белорусском языках.</p></div></div>
      <div class="feature-item animate delay-1"><div class="feature-num">02</div><div><h4>Видеопродакшн</h4><p>Промо-ролики, обзоры продукции, Reels и TikTok-контент, корпоративные фильмы, видео-отзывы. От сценария и раскадровки до съёмки, цветокоррекции и финального монтажа. Собственное студийное оборудование.</p></div></div>
      <div class="feature-item animate delay-2"><div class="feature-num">03</div><div><h4>Графический дизайн</h4><p>Баннеры для рекламы, инфографика, оформление соцсетей, презентации для инвесторов и клиентов, полиграфия. Работаем в фирменном стиле вашего бренда или разрабатываем его с нуля.</p></div></div>
      <div class="feature-item animate delay-3"><div class="feature-num">04</div><div><h4>Фото и предметная съёмка</h4><p>Имиджевая и предметная фотосъёмка для каталогов, маркетплейсов и соцсетей. Выездные съёмки в Минске и области. Ретушь, цветокоррекция и подготовка под все платформы.</p></div></div>
      <div class="feature-item animate delay-4"><div class="feature-num">05</div><div><h4>Контент-стратегия</h4><p>Разрабатываем долгосрочную стратегию контент-маркетинга: анализ аудитории, карта контента, рубрикатор, календарь публикаций, метрики эффективности. Документ, по которому ваш маркетинг работает как система.</p></div></div>
      <div class="feature-item animate delay-5"><div class="feature-num">06</div><div><h4>Управление блогом и рассылками</h4><p>Берём корпоративный блог и email-маркетинг на полное обслуживание: планирование тем, написание, вёрстка, публикация, A/B тестирование заголовков и анализ открываемости.</p></div></div>
    </div>
  </section>

  <div class="section-divider"></div>

  <section class="section">
    <div class="section-label">Тарифы контента</div>
    <h2 class="section-title">Пакеты контент-услуг</h2>
    <div class="pricing-grid">
      <div class="price-card animate">
        <h4>Текстовый</h4><div class="price-desc">Базовый контент для сайта и соцсетей</div>
        <div class="price-amount">от 350 BYN <span>/ мес</span></div>
        <ul class="price-features">
          <li>8 текстов / месяц</li>
          <li>SEO-оптимизация текстов</li>
          <li>Базовая графика</li>
          <li>Контент-план</li>
        </ul>
        <a class="price-btn price-btn-outline" href="/contact?tariff=Текстовый">Оставить заявку</a>
      </div>
      <div class="price-card featured animate delay-1">
        <h4>Мультимедиа</h4><div class="price-desc">Тексты + видео + графика</div>
        <div class="price-amount">от 890 BYN <span>/ мес</span></div>
        <ul class="price-features">
          <li>15 текстов / месяц</li>
          <li>4 видеоролика</li>
          <li>Дизайн баннеров и постов</li>
          <li>Контент-стратегия</li>
          <li>Фотосессия (1 в месяц)</li>
        </ul>
        <a class="price-btn price-btn-filled" href="/contact?tariff=Мультимедиа">Оставить заявку</a>
      </div>
      <div class="price-card animate delay-2">
        <h4>Полный продакшн</h4><div class="price-desc">Контент-агентство на аутсорсе</div>
        <div class="price-amount">от 1 900 BYN <span>/ мес</span></div>
        <ul class="price-features">
          <li>Безлимит текстового контента</li>
          <li>8+ видеороликов</li>
          <li>Полный графический дизайн</li>
          <li>Фотосессии (2 в месяц)</li>
          <li>Выделенная команда</li>
          <li>Стратегические планёрки</li>
        </ul>
        <a class="price-btn price-btn-outline" href="/contact?tariff=Полный продакшн">Оставить заявку</a>
      </div>
    </div>
  </section>

  <div class="section-divider"></div>

  <!-- EXPERT ARTICLE -->
  <section class="section">
    <div class="section-label animate">Экспертиза</div>
    <h2 class="section-title animate delay-1">Контент-маркетинг: стратегия, а не хаос</h2>
    <div class="article-section animate delay-2">
      <h3>Как выстроить контентную машину, которая работает на автопилоте</h3>
      <p>Контент ради контента — главная болезнь белорусского digital. Компании тратят тысячи рублей на тексты и видео, которые никто не читает и не смотрит. Причина проста: нет стратегии. Контент-маркетинг — это не набор постов, это система, где каждый элемент выполняет конкретную функцию в воронке продаж.</p>

      <h4>Принцип пирамиды контента</h4>
      <p>Мы строим контент по принципу пирамиды: одна большая единица (longread, видео-обзор, подкаст) дробится на десятки мелких форматов. Из одной статьи на 3000 слов рождаются 5 постов для соцсетей, 3 карусели, серия Stories и email-дайджест. Это экономит бюджет и обеспечивает единый информационный поток по всем каналам.</p>

      <h4>Видео — обязательный минимум</h4>
      <p>Тексты по-прежнему важны для SEO, но видео — для людей. Исследования показывают, что пользователи запоминают 95% информации из видео и только 10% из текста. Мы интегрируем видеоконтент на каждом этапе: видео-отзывы для доверия, обзоры для знакомства с продуктом, Reels для охвата.</p>

      <blockquote>
        <p>«Контент — это инвестиция с долгим горизонтом. Статья, написанная сегодня, будет приносить трафик через год и два. Видео-обзор продолжит генерировать просмотры и заявки. Мы строим контентные активы, которые работают на бизнес клиента годами, а не одноразовые публикации.»</p>
        <div class="expert-badge">
          <div class="expert-avatar">ЯЮ</div>
          <div>
            <div class="expert-name">Яна Юркевич</div>
            <div class="expert-role">Руководитель SMM-отдела, ЯРЧЕ</div>
          </div>
        </div>
      </blockquote>

      <h4>Измеряем всё</h4>
      <p>Каждый материал привязан к метрике: статья — к органическому трафику и позициям, пост — к охвату и переходам, email — к открываемости и кликам. Без аналитики контент — это расходы. С аналитикой — это управляемый канал роста. Мы настраиваем UTM-метки, цели в аналитике и регулярно пересматриваем контент-план на основе данных.</p>
    </div>
  </section>`;

export default function Page() {
  return (
    <>
      <link rel="stylesheet" href="/pages/content.css" />
      <main data-page="content" dangerouslySetInnerHTML={{ __html: BODY }} />
    </>
  );
}
