// AUTO-GENERATED by scripts/migrate-pages.mjs — do not edit by hand.
// Source: ../yarche/ai-employee.html
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: { absolute: "AI-сотрудник на базе OpenClaw — виртуальный работник для бизнеса | ЯРЧЕ" },
  description: "Внедрение AI-сотрудника на базе OpenClaw. Автономный виртуальный работник, который ведёт переписку, обрабатывает заявки, управляет задачами и работает 24/7. Настройка под ваш бизнес.",
  keywords: ["AI-сотрудник","OpenClaw","виртуальный сотрудник","AI-агент для бизнеса","автоматизация Минск","искусственный интеллект работник"],
  alternates: { canonical: "/ai-employee" },
  openGraph: {
    title: "AI-сотрудник на базе OpenClaw — виртуальный работник для бизнеса | ЯРЧЕ",
    description: "Внедрение AI-сотрудника на базе OpenClaw. Автономный виртуальный работник, который ведёт переписку, обрабатывает заявки, управляет задачами и работает 24/7.",
    url: "/ai-employee",
    type: 'website',
    images: [{ url: "https://yarche.by/images/og.jpg" }],
  },
};

const BODY = `<!-- HERO with special highlight -->
<section class="inner-hero" style="padding-bottom:40px;">
    <div class="hero-badge animate" style="background:rgba(255,107,0,0.15); border-color:rgba(255,107,0,0.3); color:var(--orange);">🔥 HOT — AI-сотрудник</div>
    <h1 class="delay-1">AI-сотрудник<br>на базе <span class="highlight">OpenClaw</span></h1>
    <p class="animate delay-2 mobile-hide">Не чат-бот. Не ассистент. Полноценный виртуальный работник, который думает, действует и решает задачи — как живой член команды. Только без больничных, отпусков и выгорания.</p>
    <p class="animate delay-2 mobile-show">Виртуальный работник 24/7 — без больничных и выгорания.</p>
</section>

<!-- WHAT IS IT -->
<section class="section" style="padding-top:20px;">
    <div class="section-label animate">Что это</div>
    <h2 class="section-title animate delay-1">Сотрудник, которого не нужно нанимать</h2>
    <p class="section-desc animate delay-2 mobile-hide">AI-сотрудник на базе OpenClaw — это автономный AI-агент, развёрнутый на вашей инфраструктуре, который работает через привычные каналы: Telegram, WhatsApp, Slack, email. Он не просто отвечает на вопросы — он выполняет реальные задачи: ведёт переписку с клиентами, обрабатывает заявки, управляет календарём, готовит отчёты и принимает решения в рамках заданных полномочий.</p>
    <p class="section-desc animate delay-2 mobile-show">AI-агент на вашем сервере: отвечает клиентам, обрабатывает заявки и управляет задачами через Telegram, WhatsApp и email.</p>

    <div class="article-section card-hot animate delay-3" style="margin-top:36px;"><div class="card-hot-border"></div>
      <h3 style="color:var(--orange);">Почему OpenClaw, а не обычный чат-бот?</h3>
      <p class="mobile-hide">Обычные чат-боты работают по скриптам — они отвечают на вопросы из базы знаний. AI-сотрудник на OpenClaw — это принципиально другой уровень. Это агентная система, которая видит контекст, помнит историю взаимодействий, владеет вашими инструментами и способна выполнять цепочки действий без вашего участия.</p>
      <p class="mobile-hide">OpenClaw — open-source платформа, которую CEO Nvidia Дженсен Хуанг назвал «следующим ChatGPT». Она позволяет создавать AI-агентов, которые работают на ваших серверах, подключаются к вашим системам и действуют от вашего имени. Мы берём эту мощь и настраиваем её под конкретные задачи вашего бизнеса.</p>
      <p class="mobile-show">Не скриптовый бот, а агентная система: помнит контекст, владеет вашими инструментами, действует сам. OpenClaw — платформа, которую CEO Nvidia назвал «следующим ChatGPT».</p>
    </div>
</section>

<div class="section-divider"></div>

<!-- CAPABILITIES -->
<section class="section">
    <div class="section-label animate">Возможности</div>
    <h2 class="section-title animate delay-1">Что умеет ваш AI-сотрудник</h2>
    <p class="section-desc animate delay-2 mobile-hide">Каждый AI-сотрудник настраивается индивидуально. Ниже — базовые компетенции, которые доступны из коробки. Специализированные навыки разрабатываются под ваш бизнес.</p>
    <p class="section-desc animate delay-2 mobile-show">Базовые навыки из коробки — специализированные разрабатываются под ваш бизнес.</p>
    <div class="features-list">
      <div class="feature-item animate"><div class="feature-num">01</div><div><h4>Ведёт переписку с клиентами</h4><p class="mobile-hide">Общается в Telegram, WhatsApp, Viber, email и любых мессенджерах, которые использует ваша команда. Отвечает на вопросы, уточняет детали заказа, отправляет коммерческие предложения. Говорит голосом вашего бренда — тональность, стиль и границы задаёте вы.</p><p class="mobile-show">Отвечает клиентам во всех мессенджерах голосом вашего бренда.</p></div></div>
      <div class="feature-item animate delay-1"><div class="feature-num">02</div><div><h4>Обрабатывает входящие заявки</h4><p class="mobile-hide">Принимает обращения из всех каналов, классифицирует по приоритету, квалифицирует лиды и заносит в CRM. Горячим клиентам — мгновенный ответ. Сложные вопросы — эскалация живому менеджеру с полным контекстом переписки.</p><p class="mobile-show">Квалифицирует лиды, заносит в CRM, сложные вопросы эскалирует менеджеру.</p></div></div>
      <div class="feature-item animate delay-2"><div class="feature-num">03</div><div><h4>Управляет календарём и задачами</h4><p class="mobile-hide">Планирует встречи, отправляет напоминания, создаёт задачи в вашем трекере. Может самостоятельно координировать расписание нескольких участников, находить свободные слоты и рассылать приглашения.</p><p class="mobile-show">Планирует встречи, создаёт задачи, рассылает приглашения.</p></div></div>
      <div class="feature-item animate delay-3"><div class="feature-num">04</div><div><h4>Мониторит и отчитывается</h4><p class="mobile-hide">Собирает данные из ваших систем, формирует ежедневные и еженедельные сводки, уведомляет о важных событиях. Утренний брифинг в Telegram с ключевыми метриками — без единого клика с вашей стороны.</p><p class="mobile-show">Утренний брифинг с метриками в Telegram — без единого клика.</p></div></div>
      <div class="feature-item animate delay-4"><div class="feature-num">05</div><div><h4>Работает с документами</h4><p class="mobile-hide">Обрабатывает входящие PDF, таблицы и письма. Извлекает нужные данные, заполняет шаблоны, готовит ответы. Может проверять накладные, сверять позиции и формировать сводные таблицы — всё то, на что ваши сотрудники тратят часы.</p><p class="mobile-show">Читает PDF и таблицы, заполняет шаблоны, готовит ответы.</p></div></div>
      <div class="feature-item animate delay-5"><div class="feature-num">06</div><div><h4>Учится и становится лучше</h4><p class="mobile-hide">Постоянная память, контекст 24/7 и система навыков, которые можно расширять. Чем дольше AI-сотрудник работает в вашей компании, тем глубже он понимает процессы, клиентов и специфику. Через месяц он знает ваш бизнес лучше, чем новый стажёр через полгода.</p><p class="mobile-show">С каждым днём понимает ваш бизнес глубже — навыки расширяются.</p></div></div>
    </div>
</section>

<div class="section-divider"></div>

<!-- KEY DIFFERENTIATORS -->
<section class="section">
    <div class="section-label animate">Преимущества</div>
    <h2 class="section-title animate delay-1">Почему это не «ещё один бот»</h2>
    <div class="synergy-grid" style="grid-template-columns: 1fr 1fr 1fr;">
      <div class="synergy-card animate">
        <div class="synergy-formula">На вашем сервере</div>
        <p>Данные не уходят в облака третьих лиц. OpenClaw разворачивается на вашей инфраструктуре. Полный контроль, полная приватность, соответствие законодательству РБ.</p>
      </div>
      <div class="synergy-card animate delay-1">
        <div class="synergy-formula">24/7 без перерывов</div>
        <p>Не спит, не болеет, не уходит в отпуск. Обрабатывает обращения в 3 часа ночи так же быстро, как в 10 утра. Выходные и праздники — рабочие дни вашего AI-сотрудника.</p>
      </div>
      <div class="synergy-card animate delay-2">
        <div class="synergy-formula">Мультиканальность</div>
        <p>WhatsApp, Telegram, Slack, Discord, email, SMS, Teams — AI-сотрудник присутствует везде, где общаются ваши клиенты и команда. Единая память через все каналы.</p>
      </div>
      <div class="synergy-card animate delay-3">
        <div class="synergy-formula">Проактивность</div>
        <p>Не ждёт команд. Сам напоминает о дедлайнах, информирует о проблемах, готовит утренние брифинги. Работает по расписанию (cron), реагирует на триггеры и вебхуки.</p>
      </div>
      <div class="synergy-card animate delay-4">
        <div class="synergy-formula">Интеграции</div>
        <p>Подключается к CRM, бухгалтерии, складу, Google Workspace, 1С и любым системам через API. Навыки (skills) расширяют возможности без ограничений — система модульная.</p>
      </div>
      <div class="synergy-card animate delay-5">
        <div class="synergy-formula">Масштабируемость</div>
        <p>Один AI-сотрудник заменяет 2–3 линейных специалистов. Нужно больше — разворачиваем дополнительных агентов под разные отделы: продажи, поддержка, логистика.</p>
      </div>
    </div>
</section>

<div class="section-divider"></div>

<!-- PRICING -->
<section class="section">
    <div class="section-label">Пакеты</div>
    <h2 class="section-title">Внедрение AI-сотрудника</h2>
    <p class="section-desc">Стоимость зависит от сложности интеграций и количества навыков. Все пакеты включают обучение вашей команды.</p>
    <div class="pricing-grid">
      <div class="price-card animate">
        <h4>Пилот</h4><div class="price-desc">Один AI-сотрудник, одна задача</div>
        <div class="price-amount">от 1 390 BYN</div>
        <div class="price-period">срок: 1–2 недели</div>
        <ul class="price-features">
          <li>1 канал коммуникации</li>
          <li>До 5 базовых навыков</li>
          <li>Интеграция с 1 системой</li>
          <li>Обучение на ваших данных</li>
          <li>Поддержка 1 месяц</li>
        </ul>
        <a class="price-btn price-btn-outline" href="/contact?tariff=Пилот">Оставить заявку</a>
      </div>
      <div class="price-card featured animate delay-1">
        <h4>Бизнес</h4><div class="price-desc">Полноценный AI-сотрудник</div>
        <div class="price-amount">от 2 900 BYN</div>
        <div class="price-period">срок: 2–3 недели</div>
        <ul class="price-features">
          <li>Мультиканальность</li>
          <li>До 15 навыков</li>
          <li>CRM + календарь + email</li>
          <li>Проактивные сценарии</li>
          <li>Обучение команды</li>
          <li>Поддержка 3 месяца</li>
        </ul>
        <a class="price-btn price-btn-filled" href="/contact?tariff=Бизнес">Оставить заявку</a>
      </div>
      <div class="price-card animate delay-2">
        <h4>Команда AI</h4><div class="price-desc">Несколько AI-сотрудников под отделы</div>
        <div class="price-amount">от 5 900 BYN</div>
        <div class="price-period">срок: 3–4 недели</div>
        <ul class="price-features">
          <li>2–5 AI-сотрудников</li>
          <li>Безлимит навыков</li>
          <li>Полная интеграция систем</li>
          <li>Кастомная архитектура</li>
          <li>Выделенный инженер</li>
          <li>Поддержка 6 месяцев</li>
        </ul>
        <a class="price-btn price-btn-outline" href="/contact?tariff=Команда AI">Оставить заявку</a>
      </div>
    </div>
</section>

<!-- CTA -->
<section class="section" style="text-align:center; padding-bottom:40px;">
    <h2 class="section-title animate" style="margin:0 auto 20px;">Хотите увидеть AI-сотрудника в деле?</h2>
    <p class="section-desc animate delay-1" style="margin:0 auto 40px;">Бесплатная 30-минутная консультация. Покажем демо, разберём ваши процессы и рассчитаем потенциальную экономию.</p>
    <a class="btn-primary animate delay-2" href="/contact" style="display:inline-flex;">Записаться на демо →</a>
</section>

<div class="section-divider"></div>

<!-- EXPERT ARTICLE -->
<section class="section">
    <div class="section-label animate">От первого лица</div>
    <h2 class="section-title animate delay-1">Зачем мы запустили эту услугу</h2>
    <div class="article-section animate delay-2">
      <h3>AI-сотрудник — это не фантастика, это следующий шаг для бизнеса</h3>
      <p>Мы наблюдаем за развитием AI-агентов с момента появления первых автономных систем. Когда OpenClaw вышел на сцену и доказал, что агентный подход работает — мы поняли: это то, что изменит рынок труда. Не через 10 лет. Сейчас.</p>

      <h4>Что мы увидели в своей практике</h4>
      <p>У большинства наших клиентов есть типовая проблема: 60–70% времени сотрудников уходит на рутину. Ответить на одинаковые вопросы, перенести данные из одной системы в другую, подготовить стандартный документ. Это не работа — это механическое повторение. И именно это AI-сотрудник делает идеально.</p>

      <h4>Как устроен процесс</h4>
      <p>Мы не продаём коробочное решение. Каждый AI-сотрудник проектируется под конкретную роль в вашей компании. Мы изучаем процессы, определяем зоны автоматизации, настраиваем систему навыков, подключаем к нужным каналам и системам, а затем обучаем на ваших данных. Первый рабочий прототип — через 2 недели.</p>

      <blockquote>
        <p>«Когда клиент впервые видит, как AI-сотрудник самостоятельно обработал входящую заявку, квалифицировал лида, записал его в CRM и отправил коммерческое предложение — за 40 секунд вместо 15 минут — вопросы о целесообразности отпадают. Мы не раскрываем все детали нашей методологии внедрения, но скажу одно: мы научились делать это быстро, надёжно и с гарантией результата.»</p>
        <div class="expert-badge">
          <div class="expert-avatar">ВВ</div>
          <div>
            <div class="expert-name"><a href="/team/vlad">Владислав Васильченко</a></div>
            <div class="expert-role">CEO, ЯРЧЕ</div>
          </div>
        </div>
      </blockquote>

      <h4>Что мы не рассказываем публично</h4>
      <p>Наша методология внедрения, архитектура навыков, способы обучения и подход к безопасности — это наше конкурентное преимущество. На этой странице мы показали возможности. Детали — на личной консультации. Если вам интересно узнать, как AI-сотрудник может работать именно в вашем бизнесе — оставьте заявку. Первая консультация бесплатна.</p>
    </div>
</section>`;

export default function Page() {
  return (
    <>
      <link rel="stylesheet" href="/pages/ai-employee.css" />
      <main data-page="ai-employee" dangerouslySetInnerHTML={{ __html: BODY }} />
    </>
  );
}
