#!/usr/bin/env node
/**
 * One-shot migration: legacy <slug>.html → app/<slug>/page.tsx + public/pages/<slug>.css
 *
 *   Input:  ../yarche/<slug>.html
 *   Output: app/<slug>/page.tsx
 *           public/pages/<slug>.css   (concatenated <style> blocks)
 *
 * Body is preserved verbatim and rendered with dangerouslySetInnerHTML. The
 * shared nav/footer/scripts already live in app/layout.tsx + GlobalScripts,
 * so we only emit the page-specific <main> content.
 *
 * Re-runnable: overwrites generated files. Won't touch the home page.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const PROJECT = resolve(HERE, '..');
const LEGACY = resolve(PROJECT, '..', 'yarche');

// slug ↔ legacy file. Each generated route is app/<slug>/page.tsx.
const PAGES = [
  { slug: 'services', file: 'services.html' },
  { slug: 'web', file: 'web.html' },
  { slug: 'ai', file: 'ai.html' },
  { slug: 'ai-employee', file: 'ai-employee.html' },
  { slug: 'seo', file: 'seo.html' },
  { slug: 'content', file: 'content.html' },
  { slug: 'tg-bots', file: 'tg-bots.html' },
  { slug: 'contact', file: 'contact.html' },
  // /blog and /blog-post are NOT migrated by this script: /blog has a hand-written
  // RSC page (reads posts.json server-side) and /blog/[slug] is dynamic.
  { slug: 'cases', file: 'cases/index.html' },
];

const SPECIAL = {
  // 404.html is rendered via Next's not-found.tsx — handled separately below.
};

function readSrc(file) {
  return readFileSync(join(LEGACY, file), 'utf8');
}

/** Extract all <style>…</style> bodies (in order) and concatenate them. */
function extractStyles(html) {
  const re = /<style[^>]*>([\s\S]*?)<\/style>/gi;
  const chunks = [];
  let m;
  while ((m = re.exec(html))) chunks.push(m[1]);
  return chunks.join('\n\n/* --- next style block --- */\n\n');
}

/** Inner <main>…</main> (greedy across newlines). */
function extractMain(html) {
  const m = html.match(/<main[^>]*>([\s\S]*?)<\/main>/i);
  if (!m) throw new Error('no <main> block found');
  return m[1].trim();
}

function metaContent(html, name) {
  // name can be `name="..."` or `property="..."`.
  const re = new RegExp(
    `<meta\\s+(?:name|property)="${name.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\$&')}"\\s+content="([^"]*)"`,
    'i',
  );
  const m = html.match(re);
  return m ? m[1] : null;
}

function extractTitle(html) {
  const m = html.match(/<title>([\s\S]*?)<\/title>/i);
  return m ? m[1].trim() : '';
}

function extractCanonical(html) {
  const m = html.match(/<link\s+rel="canonical"\s+href="([^"]+)"/i);
  return m ? m[1] : null;
}

/**
 * Strip everything from the legacy body that is now provided by the shared
 * layout: redundant theme/cursor/nav/footer scripts and the swup/widget loader.
 * We only need the visible content of <main>.
 */
function cleanMainBody(body) {
  // Inline scripts inside <main> are rare and likely unused; drop them for safety.
  return body.replace(/<script[\s\S]*?<\/script>/gi, '').trim();
}

function tsEscape(str) {
  // Safe to embed inside backticks: only escape ${ and `.
  return String(str).replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

function quote(str) {
  return JSON.stringify(str ?? '');
}

function pageTsx({ slug, title, description, keywords, canonical, ogTitle, ogDesc, ogImage, body }) {
  const ogTitleFinal = ogTitle || title;
  const ogDescFinal = ogDesc || description;
  const canonicalPath = canonical
    ? canonical.replace(/^https?:\/\/[^/]+/, '') || '/'
    : `/${slug}`;
  const ogImageLine = ogImage
    ? `  openGraph: {\n    title: ${quote(ogTitleFinal)},\n    description: ${quote(ogDescFinal)},\n    url: ${quote(canonicalPath)},\n    type: 'website',\n    images: [{ url: ${quote(ogImage.startsWith('http') ? ogImage : ogImage)} }],\n  },`
    : `  openGraph: {\n    title: ${quote(ogTitleFinal)},\n    description: ${quote(ogDescFinal)},\n    url: ${quote(canonicalPath)},\n    type: 'website',\n  },`;

  const keywordsLine =
    keywords && keywords.trim()
      ? `  keywords: ${JSON.stringify(keywords.split(',').map((s) => s.trim()).filter(Boolean))},\n`
      : '';

  return `// AUTO-GENERATED by scripts/migrate-pages.mjs — do not edit by hand.
// Source: ../yarche/${SPECIAL[slug]?.source || ''}${SPECIAL[slug] ? '' : (slug === 'cases' ? 'cases/index.html' : slug + '.html')}
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: { absolute: ${quote(title)} },
  description: ${quote(description)},
${keywordsLine}  alternates: { canonical: ${quote(canonicalPath)} },
${ogImageLine}
};

const BODY = \`${tsEscape(body)}\`;

export default function Page() {
  return (
    <>
      <link rel="stylesheet" href="/pages/${slug}.css" />
      <main data-page="${slug}" dangerouslySetInnerHTML={{ __html: BODY }} />
    </>
  );
}
`;
}

function migrate({ slug, file }) {
  const src = readSrc(file);
  const css = extractStyles(src);
  const body = cleanMainBody(extractMain(src));
  const title = extractTitle(src);
  const description = metaContent(src, 'description') || '';
  const keywords = metaContent(src, 'keywords') || '';
  const canonical = extractCanonical(src);
  const ogTitle = metaContent(src, 'og:title');
  const ogDesc = metaContent(src, 'og:description');
  const ogImage = metaContent(src, 'og:image');

  const cssPath = join(PROJECT, 'public', 'pages', `${slug}.css`);
  const pagePath = join(PROJECT, 'app', slug, 'page.tsx');

  mkdirSync(dirname(cssPath), { recursive: true });
  mkdirSync(dirname(pagePath), { recursive: true });

  writeFileSync(cssPath, css, 'utf8');
  writeFileSync(
    pagePath,
    pageTsx({ slug, title, description, keywords, canonical, ogTitle, ogDesc, ogImage, body }),
    'utf8',
  );

  console.log(
    `  ✓ ${slug.padEnd(12)} → app/${slug}/page.tsx (${body.length} bytes body, ${css.length} bytes css)`,
  );
}

// 404 → app/not-found.tsx (Next's special file)
function migrate404() {
  const src = readSrc('404.html');
  const css = extractStyles(src);
  const body = cleanMainBody(extractMain(src));
  const title = extractTitle(src);
  const description = metaContent(src, 'description') || '';

  writeFileSync(join(PROJECT, 'public', 'pages', '404.css'), css, 'utf8');

  const file = `// AUTO-GENERATED by scripts/migrate-pages.mjs — do not edit by hand.
// Source: ../yarche/404.html
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: { absolute: ${quote(title)} },
  description: ${quote(description)},
};

const BODY = \`${tsEscape(body)}\`;

export default function NotFound() {
  return (
    <>
      <link rel="stylesheet" href="/pages/404.css" />
      <main dangerouslySetInnerHTML={{ __html: BODY }} />
    </>
  );
}
`;
  writeFileSync(join(PROJECT, 'app', 'not-found.tsx'), file, 'utf8');
  console.log('  ✓ 404          → app/not-found.tsx');
}

function main() {
  console.log(`Migrating ${PAGES.length} page(s) + 404 →\n`);
  for (const p of PAGES) {
    try {
      migrate(p);
    } catch (err) {
      console.error(`  ✗ ${p.slug}: ${err.message}`);
    }
  }
  try {
    migrate404();
  } catch (err) {
    console.error(`  ✗ 404: ${err.message}`);
  }
  console.log('\nRunning dedup...\n');
  import('./dedup-pages-css.mjs');
}

main();
