// AUTO-GENERATED by scripts/migrate-pages.mjs — do not edit by hand.
// Source: ../yarche/web.html
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: { absolute: "Создание сайтов в Минске — лендинги, магазины, веб-приложения | ЯРЧЕ" },
  description: "Разработка сайтов для бизнеса в Беларуси: лендинги, корпоративные сайты, интернет-магазины с ЕРИП. UX-дизайн, SEO-оптимизация, техподдержка. От 1 500 BYN.",
  keywords: ["создание сайтов Минск","разработка сайтов Беларусь","интернет-магазин","лендинг","веб-разработка"],
  alternates: { canonical: "/web" },
  openGraph: {
    title: "Создание сайтов в Минске — лендинги, магазины, веб-приложения | ЯРЧЕ",
    description: "Разработка сайтов для бизнеса в Беларуси: лендинги, корпоративные сайты, интернет-магазины с ЕРИП. UX-дизайн, SEO-оптимизация, техподдержка. От 1 500 BYN.",
    url: "/web",
    type: 'website',
    images: [{ url: "https://yarche.by/images/og.jpg" }],
  },
};

const BODY = `<section class="inner-hero">
    <div class="hero-badge animate" style="background:rgba(255,107,0,0.15); border-color:rgba(255,107,0,0.3); color:var(--orange);">🔥 HOT — Создание сайтов</div>
    <h1 class="delay-1">Сайты, которые <span class="highlight">конвертируют</span></h1>
    <p class="animate delay-2">Проектируем и разрабатываем веб-решения, которые не просто красиво выглядят, а приносят деньги. От лендинга до сложного e-commerce — с фокусом на UX, скорость и конверсию.</p>
  </section>

  <section class="section" style="padding-top:20px;">
    <div class="section-label animate">Что разрабатываем</div>
    <h2 class="section-title animate delay-1">Веб-решения любой сложности</h2>
    <p class="section-desc animate delay-2">Каждый проект начинается с прототипа и пользовательских сценариев. Мы не рисуем макеты — мы проектируем путь клиента от первого визита до покупки.</p>
    <div class="features-list">
      <div class="feature-item animate"><div class="feature-num">01</div><div><h4>Лендинги высокой конверсии</h4><p>Продающие одностраничники для запуска продуктов, рекламных кампаний и лидогенерации. Каждый экран проектируется по принципам нейромаркетинга: заголовок-крючок, социальные доказательства, чёткий CTA. Средняя конверсия наших лендингов — 8–12%.</p></div></div>
      <div class="feature-item animate delay-1"><div class="feature-num">02</div><div><h4>Корпоративные сайты</h4><p>Многостраничные сайты с продуманной информационной архитектурой, CMS-панелью управления и интеграцией с CRM. Мультиязычность, блог, портфолио, калькуляторы — всё, что нужно для презентации бизнеса и генерации заявок.</p></div></div>
      <div class="feature-item animate delay-2"><div class="feature-num">03</div><div><h4>Интернет-магазины</h4><p>Полноценные e-commerce платформы с каталогом, фильтрами, корзиной, интеграцией ЕРИП и банковских карт. Связка со складом, 1С, службами доставки. Личный кабинет покупателя с историей заказов и программой лояльности.</p></div></div>
      <div class="feature-item animate delay-3"><div class="feature-num">04</div><div><h4>Веб-приложения и SaaS</h4><p>Кастомные платформы на React, Vue, Node.js: CRM-системы, личные кабинеты, маркетплейсы, системы бронирования. Микросервисная архитектура, REST API, real-time функционал через WebSocket.</p></div></div>
      <div class="feature-item animate delay-4"><div class="feature-num">05</div><div><h4>Редизайн без потери позиций</h4><p>Обновляем устаревшие сайты с сохранением SEO-веса: правильные редиректы, миграция контента, сохранение структуры URL. Переводим с Bitrix на WordPress, с Tilda на кастом — безболезненно и без просадки трафика.</p></div></div>
      <div class="feature-item animate delay-5"><div class="feature-num">06</div><div><h4>Техподдержка и развитие</h4><p>Абонентская поддержка после запуска: мониторинг аптайма, обновление CMS и плагинов, бэкапы, защита от взлома. Ежемесячное развитие: новые страницы, A/B тесты, интеграция новых сервисов.</p></div></div>
    </div>
  </section>

  <div class="section-divider"></div>

  <section class="section">
    <div class="section-label">Цены на разработку</div>
    <h2 class="section-title">Стоимость разработки сайтов</h2>
    <div class="pricing-grid">

      <!-- MERGED: Лендинг + Корпоративный -->
      <div class="price-card featured-combo animate">
        <h4>Лендинг / Корпоративный</h4>
        <div class="price-desc">Одностраничник или многостраничный сайт компании</div>
        <div class="price-amount">от 650 BYN</div>
        <div class="price-period">срок: 2–10 дней</div>
        <ul class="price-features">
          <li>Уникальный дизайн под бренд</li>
          <li>Адаптивная вёрстка</li>
          <li>До 15 страниц (корп. сайт)</li>
          <li>CMS-система по желанию</li>
          <li>Форма заявки + CRM</li>
          <li>SEO-оптимизация из коробки</li>
          <li>Мультиязычность</li>
          <li>Поддержка 2 месяца</li>
        </ul>
        <a class="price-btn price-btn-orange" href="/contact?tariff=Лендинг">Оставить заявку</a>
      </div>

      <!-- Интернет-магазин -->
      <div class="price-card animate delay-1">
        <h4>Интернет-магазин</h4>
        <div class="price-desc">Полноценная e-commerce платформа</div>
        <div class="price-amount">от 2 900 BYN</div>
        <div class="price-period">срок: 1–3 недели</div>
        <ul class="price-features">
          <li>Каталог и фильтры</li>
          <li>Корзина и оплата (ЕРИП)</li>
          <li>Личный кабинет</li>
          <li>Интеграция со складом</li>
          <li>SEO-оптимизация</li>
          <li>Поддержка 5 месяцев</li>
        </ul>
        <a class="price-btn price-btn-outline" href="/contact?tariff=Интернет-магазин">Оставить заявку</a>
      </div>

      <!-- React / Next.js — WOW card -->
      <div class="price-card react-card animate delay-2">
        <div class="react-bg-cover"></div>
        <div class="react-particles">
          <span></span><span></span><span></span><span></span>
          <span></span><span></span><span></span><span></span>
        </div>
        <div class="react-card-inner">
          <div class="react-badge">⚛ React + Next.js</div>
          <h4>Веб-приложение</h4>
          <div class="price-desc">SPA / SSR на современном стеке — скорость, SEO и масштаб</div>
          <div class="price-amount">от 2 900 BYN</div>
          <div class="price-period">срок: 2–6 недель · рынок: $3&nbsp;000–$15&nbsp;000</div>
          <ul class="price-features">
            <li>React 18 + Next.js 14 (App Router)</li>
            <li>SSR / SSG — мгновенная загрузка</li>
            <li>SEO из коробки (серверный рендер)</li>
            <li>TypeScript + чистая архитектура</li>
            <li>REST / GraphQL / tRPC API</li>
            <li>CI/CD + деплой на Vercel / VPS</li>
            <li>Core Web Vitals 95+</li>
            <li>Поддержка 6 месяцев</li>
          </ul>
          <div class="react-examples">
            <a href="#" title="Пример">SaaS-платформа</a>
            <a href="#" title="Пример">Маркетплейс</a>
            <a href="#" title="Пример">Дашборд</a>
            <a href="#" title="Пример">Портал</a>
          </div>
          <a class="price-btn price-btn-react" href="/contact?tariff=React+Next.js">Обсудить проект</a>
        </div>
      </div>

    </div>
  </section>

  <div class="section-divider"></div>

  <!-- EXPERT ARTICLE -->
  <section class="section">
    <div class="section-label animate">Экспертиза</div>
    <h2 class="section-title animate delay-1">Что отличает сайт за&nbsp;1&nbsp;500&nbsp;BYN от сайта за&nbsp;15&nbsp;000</h2>
    <div class="article-section animate delay-2">
      <h3>Архитектура, скорость и конверсия — три кита современной веб-разработки</h3>
      <p>На рынке Беларуси можно заказать сайт за 500 рублей на Tilda или за 50 000 на кастомной разработке. Разница не в количестве страниц — а в том, как сайт влияет на ваш бизнес. Дешёвый сайт-визитка может работать. Но когда бизнес растёт, шаблонное решение начинает тормозить — в буквальном смысле.</p>

      <h4>Скорость загрузки = деньги</h4>
      <p>Каждая дополнительная секунда загрузки снижает конверсию на 7%. Сайт на перегруженной Tilda с десятками неоптимизированных изображений грузится 5–8 секунд на мобильном. Наши проекты проходят аудит Core Web Vitals и укладываются в 2 секунды. Это не перфекционизм — это прямое влияние на количество заявок.</p>

      <h4>UX-проектирование: не дизайн, а инженерия</h4>
      <p>Мы не «делаем красивый дизайн» — мы проектируем пользовательский опыт. Каждый элемент на странице имеет цель: привлечь внимание, вызвать доверие, подтолкнуть к действию. Прототипы тестируются на реальных пользователях до начала разработки. Это дороже, но разница в конверсии — в 2–3 раза.</p>

      <blockquote>
        <p>«Сайт — это не расходная статья, это актив бизнеса. Правильно спроектированный сайт окупает себя в первый месяц работы. Мы считаем ROI каждого проекта и даём клиенту понятные цифры: сколько посетителей, сколько заявок, сколько продаж. Если сайт не приносит денег — мы что-то делаем не так.»</p>
        <div class="expert-badge">
          <div class="expert-avatar">ВВ</div>
          <div>
            <div class="expert-name"><a href="/team/vlad">Владислав Васильченко</a></div>
            <div class="expert-role">CEO, ЯРЧЕ</div>
          </div>
        </div>
      </blockquote>

      <h4>Интеграции: сайт как центр экосистемы</h4>
      <p>Современный сайт не существует изолированно. Он связан с CRM, аналитикой, рекламными кабинетами, складом, бухгалтерией и мессенджерами. Мы закладываем интеграции на этапе архитектуры, а не прикручиваем костыли после запуска. Результат — сквозная аналитика от клика по рекламе до оплаты заказа.</p>
    </div>
  </section>`;

export default function Page() {
  return (
    <>
      <link rel="stylesheet" href="/pages/web.css" />
      <main data-page="web" dangerouslySetInnerHTML={{ __html: BODY }} />
    </>
  );
}
