// AUTO-GENERATED by scripts/migrate-pages.mjs — do not edit by hand.
// Source: ../yarche/web.html
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: { absolute: "Создание сайтов в Минске — лендинги, магазины, веб-приложения | ЯРЧЕ" },
  description: "Разработка сайтов для бизнеса в Беларуси: лендинги, корпоративные сайты, интернет-магазины с ЕРИП. UX-дизайн, SEO-оптимизация, техподдержка. От 1 500 BYN.",
  keywords: ["создание сайтов Минск","разработка сайтов Беларусь","интернет-магазин","лендинг","веб-разработка"],
  alternates: { canonical: "/web" },
  openGraph: {
    title: "Создание сайтов в Минске — лендинги, магазины, веб-приложения | ЯРЧЕ",
    description: "Разработка сайтов для бизнеса в Беларуси: лендинги, корпоративные сайты, интернет-магазины с ЕРИП. UX-дизайн, SEO-оптимизация, техподдержка. От 1 500 BYN.",
    url: "/web",
    type: 'website',
    images: [{ url: "https://yarche.by/images/og.jpg" }],
  },
};

const BODY = `<section class="inner-hero">
    <div class="hero-badge animate" style="background:rgba(255,107,0,0.15); border-color:rgba(255,107,0,0.3); color:var(--orange);">🔥 HOT — Создание сайтов</div>
    <h1 class="animate delay-1">Сайты, которые <span class="highlight">конвертируют</span></h1>
    <p class="animate delay-2">Проектируем и разрабатываем веб-решения, которые не просто красиво выглядят, а приносят деньги. От лендинга до сложного e-commerce — с фокусом на UX, скорость и конверсию.</p>
  </section>

  <section class="section" style="padding-top:20px;">
    <div class="section-label animate">Что разрабатываем</div>
    <h2 class="section-title animate delay-1">Веб-решения любой сложности</h2>
    <p class="section-desc animate delay-2">Каждый проект начинается с прототипа и пользовательских сценариев. Мы не рисуем макеты — мы проектируем путь клиента от первого визита до покупки.</p>
    <div class="features-list">
      <div class="feature-item animate" href="/web/landing"><div class="feature-num">01</div><div><h4>Лендинги высокой конверсии</h4><p>Продающие одностраничники для запуска продуктов, рекламных кампаний и лидогенерации. Каждый экран проектируется по принципам нейромаркетинга: заголовок-крючок, социальные доказательства, чёткий CTA. Средняя конверсия наших лендингов — 8–12%.</p><span class="service-link">Подробнее →</span></div></div>
      <div class="feature-item animate delay-1" href="/web/corporate"><div class="feature-num">02</div><div><h4>Корпоративные сайты</h4><p>Многостраничные сайты с продуманной информационной архитектурой, CMS-панелью управления и интеграцией с CRM. Мультиязычность, блог, портфолио, калькуляторы — всё, что нужно для презентации бизнеса и генерации заявок.</p><span class="service-link">Подробнее →</span></div></div>
      <div class="feature-item animate delay-2" href="/web/shop"><div class="feature-num">03</div><div><h4>Интернет-магазины</h4><p>Полноценные e-commerce платформы с каталогом, фильтрами, корзиной, интеграцией ЕРИП и банковских карт. Связка со складом, 1С, службами доставки. Личный кабинет покупателя с историей заказов и программой лояльности.</p><span class="service-link">Подробнее →</span></div></div>
      <div class="feature-item animate delay-3" href="/web/app"><div class="feature-num">04</div><div><h4>Веб-приложения и SaaS</h4><p>Кастомные платформы на React, Vue, Node.js: CRM-системы, личные кабинеты, маркетплейсы, системы бронирования. Микросервисная архитектура, REST API, real-time функционал через WebSocket.</p><span class="service-link">Подробнее →</span></div></div>
      <div class="feature-item animate delay-4" href="/web/redesign"><div class="feature-num">05</div><div><h4>Редизайн без потери позиций</h4><p>Обновляем устаревшие сайты с сохранением SEO-веса: правильные редиректы, миграция контента, сохранение структуры URL. Переводим с Bitrix на WordPress, с Tilda на кастом — безболезненно и без просадки трафика.</p><span class="service-link">Подробнее →</span></div></div>
      <div class="feature-item animate delay-5" href="/web/support"><div class="feature-num">06</div><div><h4>Техподдержка и развитие</h4><p>Абонентская поддержка после запуска: мониторинг аптайма, обновление CMS и плагинов, бэкапы, защита от взлома. Ежемесячное развитие: новые страницы, A/B тесты, интеграция новых сервисов.</p><span class="service-link">Подробнее →</span></div></div>
    </div>
  </section>

  <div class="section-divider"></div>

  <section class="section">
    <div class="section-label">Цены на разработку</div>
    <h2 class="section-title">Стоимость разработки сайтов</h2>
    <div class="pricing-grid">

      <!-- MERGED: Лендинг + Корпоративный -->
      <div class="price-card featured-combo animate">
        <h4>Лендинг / Корпоративный</h4>
        <div class="price-desc">Одностраничник или многостраничный сайт компании</div>
        <div class="price-amount">от 650 BYN</div>
        <div class="price-period">срок: 2–10 дней</div>
        <ul class="price-features">
          <li>Уникальный дизайн под бренд</li>
          <li>Адаптивная вёрстка</li>
          <li>До 15 страниц (корп. сайт)</li>
          <li>Форма заявки + CRM</li>
          <li>SEO-оптимизация из коробки</li>
          <li>Поддержка 1 месяц</li>
          <li class="is-addon">CMS-система</li>
          <li class="is-addon">Мультиязычность</li>
        </ul>
        <a class="price-btn price-btn-orange" href="/contact?tariff=Лендинг">Оставить заявку</a>
      </div>

      <!-- Интернет-магазин -->
      <div class="price-card animate delay-1">
        <h4>Интернет-магазин</h4>
        <div class="price-desc">Полноценная e-commerce платформа</div>
        <div class="price-amount">от 2 900 BYN</div>
        <div class="price-period">срок: 1–3 недели</div>
        <ul class="price-features">
          <li>Каталог и фильтры</li>
          <li>Корзина и оплата (ЕРИП)</li>
          <li>Личный кабинет</li>
          <li>Интеграция со складом</li>
          <li>SEO-оптимизация</li>
          <li>Поддержка 3 месяца</li>
        </ul>
        <a class="price-btn price-btn-outline" href="/contact?tariff=Интернет-магазин">Оставить заявку</a>
      </div>

      <!-- React / Next.js — WOW card -->
      <div class="price-card react-card animate delay-2">
        <div class="react-bg-cover"></div>
        <div class="react-particles">
          <span></span><span></span><span></span><span></span>
          <span></span><span></span><span></span><span></span>
        </div>
        <div class="react-card-inner">
          <div class="react-badge">⚛ React + Next.js</div>
          <h4>Веб-приложение</h4>
          <div class="price-desc">SPA / SSR на современном стеке — скорость, SEO и масштаб</div>
          <div class="price-amount">от 2 900 BYN</div>
          <div class="price-period">срок: 2–6 недель · рынок: $3&nbsp;000–$15&nbsp;000</div>
          <ul class="price-features">
            <li>React + Next.js — стек Notion и TikTok</li>
            <li>Открывается за 1–2 секунды</li>
            <li>Поисковики видят весь контент сразу</li>
            <li>Чистый код, легко обновлять через годы</li>
            <li>Интеграции: CRM, оплата, склад, 1С</li>
            <li>Обновления без простоев</li>
            <li>Зелёные метрики Google — выше в поиске</li>
            <li>Поддержка 3 месяца</li>
          </ul>
          <div class="react-examples">
            <span>SaaS-платформа</span>
            <span>Маркетплейс</span>
            <span>Дашборд</span>
            <span>Портал</span>
          </div>
          <a class="price-btn price-btn-react" href="/web/quote/react">Обсудить проект</a>
        </div>
      </div>

    </div>
  </section>

  <div class="section-divider"></div>

  <!-- EXPERT COMPARE TABLE -->
  <section class="section">
    <div class="section-label animate">Экспертиза</div>
    <h2 class="section-title animate delay-1">Шаблон или кастом — в чём разница</h2>
    <div class="compare-table-wrap animate delay-2">
      <table class="compare-table">
        <thead>
          <tr>
            <th></th>
            <th>Шаблон / Tilda</th>
            <th>Наш кастом</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Скорость загрузки</td>
            <td>5–8 сек на мобильном</td>
            <td>1–2 сек, Core Web Vitals в зелёной зоне</td>
          </tr>
          <tr>
            <td>Кастомизация дизайна</td>
            <td>в рамках готового шаблона</td>
            <td>любая, без потолка</td>
          </tr>
          <tr>
            <td>SEO</td>
            <td>ограниченное, чужой код</td>
            <td>полный контроль над разметкой</td>
          </tr>
          <tr>
            <td>Интеграции (CRM, склад, 1С, ЕРИП)</td>
            <td>5–10 готовых модулей</td>
            <td>любая — через API</td>
          </tr>
          <tr>
            <td>Стоимость на масштабе</td>
            <td>растёт с трафиком (тарифы конструктора)</td>
            <td>фикс — свой сервер</td>
          </tr>
          <tr>
            <td>Перенос / редизайн в будущем</td>
            <td>с потерей трафика и кода</td>
            <td>без потерь, всё ваше</td>
          </tr>
        </tbody>
      </table>
    </div>
  </section>`;

export default function Page() {
  return (
    <>
      <link rel="stylesheet" href="/pages/web.css" />
      <main data-page="web" dangerouslySetInnerHTML={{ __html: BODY }} />
    </>
  );
}
